
#MGT 6203 - association rules companion file with R scripts
# LOADING THE NECESSARY PACKAGES


# install the association rules package before you get started...
# if you've already installed it, this command will make sure the package is up to date.

#load the packages for association rules and R sample datasets

if (!require(arules)) install.packages("arules")
library(arules)
if (!require(arulesViz)) install.packages("arulesViz")
library(arulesViz)
if (!require(datasets)) install.packages("datasets")
library(datasets)


# LOADING THE DATA & SUMMARY STATISTICS

data("Groceries")
# summary statistics
summary(Groceries)
inspect(head(Groceries,10))

# plot the 'count' of each grocery item appearing in the dataset,
#from most common on down, but only show the first 20
itemFrequencyPlot(Groceries,topN=20,type="absolute")

# RETRIEVAL OF ASSOCIATION RULES


#the command to generate association rules in R is called apriori,
#which refers to the apriori algorithm. We will assign the algorithm's
#output to 'rules', which is a data frame. 
#some notes: you always have to specify the min support and min confidence
#rules that do not have at least this support and confidence will be ignored
rules <- apriori(Groceries,parameter=list(supp = 0.001, conf=0.5))

#because the support and confidence results may go to many decimal places,
#we will first specify that we only want to see two decimal places for any
#numeric output
options(digits=2)

#we'll now ask R to summarize the set of rules it generated from our data
#this tells us the number of rules generated by length (number of items),
#amongst other things
inspect(rules[1:5])

summary(rules)


# inspect rules by sorting within one command - here we sort by support/confidence/lift and return
# top 3 rules along with their measures of support, confidence and lift.
inspect(head(sort(rules, by ="support"),3))
inspect(head(sort(rules, by ="confidence"),3))
inspect(head(sort(rules, by ="lift"),3))

#now lets generate rules where we fix some values in the LHS 
#say we only want to include rules where whole milk is on the LHS...
inspect(subset(rules, subset = lhs %pin% "whole milk"))


#extract subsets
subrules1 <-rules[quality(rules)$confidence > 0.8]
subrules2<-head(sort(rules,by="lift"),10)



# VISUALIZATION


#the arulesViz packages lets us visualize our results, and we can even make an interactive plot to pick 
#rules graphically and inspect them. The plot appears in the bottom right of your screen when you run this.
plot(rules,engine="interactive")
# plotting as a graph 
plot(subrules2,method="graph")

plot(rules)
plot(rules, measure = c("support", "lift"), shading = "confidence")
plot(rules, method = "two-key plot")
plot(rules, method = "grouped")
plot(subrules2, method = "grouped")
plot(rules, method = "grouped", control = list(k = 5))
sel <- plot(rules, method = "grouped", interactive = TRUE)

#save for gephi
# saveAsGraph(head(rules, n = 1000, by = "lift"), file = "rules.graphml")

plot(subrules2, method = "paracoord")

#it is possible to pin a value on the RHS too, and to pin values on both sides
#at the same time. I don't want to get into it here, but you can explore 
#further if it's of interest to you, on Stack Overflow:
#http://stackoverflow.com/questions/27926131/how-to-get-items-for-both-lhs-and-rhs-for-only-specific-columns-in-arules

#it is also possible to examine rules with more than 1 item on the RHS. However, that is not
#the default implementation in most statistical software packages.
#This is because the number of rules to consider grows massively as you allow any number of
#items to appear on the RHS. Here's a brief description of a workaround though:
#http://r.789695.n4.nabble.com/how-to-change-number-of-itemes-appeare-in-right-hand-side-of-the-rule-with-apriori-in-R-arules-td1559955.html